#index:
#    path: /
#    controller: App\Controller\DefaultController::index
principal:
    resource: '../src/CorredoresRioja/Resources/routing/routes.yml'
    
corredores:
    resource: '../src/CorredoresRioja/Resources/routing/routes_corredor.yaml'
    prefix: 
        /corredores
    