index:
    path:
        es: /
        en: /
    
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: '@corredores/portada.html.twig'
        
logout:
    path: /logout